name: "Digital Health Blog"
title: "Digital Health Blog"
description: "Technological changes in the health sector."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /Bernadettenakazibwe.github.io

permalink: /:title/

authors:
  Bernadette:
    name: Bernadette
    display_name: Bernadette
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: bernadettenakazibwe@gmail.com
        description: "Some of the medical technologies in hospitals today."
 
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
paginate: 6
paginate_path: /page:num/
    
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About

