name: Bernadette Nakazibwe

description: Student at Deggendorf Institute of Technology, Bachelor of Science in Health Informatics.


avatar: C:\Users\BERNADETTE\OneDrive\Pictures\IMG-20221029-WA0016.jpg


url: Bernadettenakazibwe.github.io

footerlinks:


permalink: /title/contact/privancy
